INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (1,'Anchovies','USD 1.00',1, 'anchovies.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (2,'Sausage','USD 1.00',1,'sausage.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (3,'Pepperoni','USD 1.00',1,'pepperoni.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (5,'Chicken','USD 1.00',1,'chicken.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (6,'Meatballs','USD 1.00',1,'meatballs.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (7,'Ham','USD 1.00',1,'ham.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (8,'Steak','USD 1.00',1,'steak.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (9,'Bacon','USD 1.00',1,'bacon.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (10,'Beef','USD 1.00',1,'beef.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (11,'Salami','USD 1.00',1,'salami.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (12,'Spinach','USD 1.00',3,'spinach.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (13,'Mushrooms','USD 1.00',3,'mushrooms.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (14,'Red Onion','USD 1.00',3,'red_onion.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (15,'Onion','USD 1.00',3,'onion.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (16,'Banana Peppers','USD 1.00',3,'banana_peppers.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (17,'Pineapple','USD 1.00',3,'pineapple.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (18,'Jalapeno','USD 1.00',3,'jalapeno.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (19,'Black Olive','USD 1.00',3,'black_olive.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (20,'Green Pepper','USD 1.00',3,'green_pepper.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (21,'Tomatoes','USD 1.00',3,'tomato.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (22,'White Sauce','USD 0.25',4,'white_sauce.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (23,'Classic Red','USD 0.25',4,'classic_red_sauce.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (24,'Sweet Red','USD 0.25',4,'sweet_red_sauce.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (25,'Spicy Red','USD 0.25',4,'spicy_red_sauce.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (26,'Roasted Garlic','USD 1.00',3,'garlic.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (27,'Feta Cheese','USD 1.00',2,'feta.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (28,'Cheddar Cheese','USD 1.00',2,'cheddar.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (29,'Shaved Parmesan','USD 1.00',2,'shaved_parmesan.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (30,'Parmesan','USD 1.00',2,'parmesan.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (31,'Mozzarella','USD 1.00',2,'mozzarella.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (32,'Taco','USD 0.25',4,'taco_sauce.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (33,'Buffalo','USD 0.25',4,'buffalo.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (34,'Pesto','USD 0.25',4,'pesto.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (35,'BBQ','USD 0.25',4,'bbq_sauce.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (36,'Goat','USD 1.00',2,'goat.gif');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (37,'Ricotta','USD 1.00',2,'ricotta.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (38,'Blue','USD 1.00',2,'blue.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (39,'Artichoke','USD 1.00',3,'artichoke.webp');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (40,'Basil','USD 1.00',3,'basil.webp');
